# Generated by Django 4.1.7 on 2023-02-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model1',
            name='pole3',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
