# Generated by Django 4.1.7 on 2023-02-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0002_model1_pole3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model1',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
