# Generated by Django 4.1.7 on 2023-02-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0003_alter_model1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole1', models.IntegerField()),
                ('pole2', models.CharField(max_length=45)),
                ('pole3', models.TextField()),
            ],
        ),
    ]
