# Generated by Django 4.1.7 on 2023-03-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0004_model2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model2',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterField(
            model_name='model2',
            name='pole3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site1.model1'),
        ),
    ]
