# Generated by Django 4.1.7 on 2023-03-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site1', '0005_alter_model2_options_alter_model2_pole3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model2',
            name='pole3',
        ),
        migrations.AddField(
            model_name='model2',
            name='pole4',
            field=models.ManyToManyField(to='site1.model1'),
        ),
    ]
